# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/chris/Documents/Mémoire/myproject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/chris/Documents/Mémoire/myproject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chris/Documents/Mémoire/myproject/CMakeFiles /Users/chris/Documents/Mémoire/myproject//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chris/Documents/Mémoire/myproject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/chris/Documents/Mémoire/myproject/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named myproject

# Build rule for target.
myproject: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 myproject
.PHONY : myproject

# fast build rule for target.
myproject/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/build
.PHONY : myproject/fast

#=============================================================================
# Target rules for targets named damien

# Build rule for target.
damien: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 damien
.PHONY : damien

# fast build rule for target.
damien/fast:
	$(MAKE) $(MAKESILENT) -f externals/FuxCP4/FuxCP/c++/CMakeFiles/damien.dir/build.make externals/FuxCP4/FuxCP/c++/CMakeFiles/damien.dir/build
.PHONY : damien/fast

externals/JUCE/modules/juce_audio_basics/juce_audio_basics.o: externals/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o
.PHONY : externals/JUCE/modules/juce_audio_basics/juce_audio_basics.o

# target to build an object file
externals/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o
.PHONY : externals/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o

externals/JUCE/modules/juce_audio_basics/juce_audio_basics.i: externals/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i
.PHONY : externals/JUCE/modules/juce_audio_basics/juce_audio_basics.i

# target to preprocess a source file
externals/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i
.PHONY : externals/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i

externals/JUCE/modules/juce_audio_basics/juce_audio_basics.s: externals/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s
.PHONY : externals/JUCE/modules/juce_audio_basics/juce_audio_basics.s

# target to generate assembly for a file
externals/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s
.PHONY : externals/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s

externals/JUCE/modules/juce_audio_devices/juce_audio_devices.o: externals/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o
.PHONY : externals/JUCE/modules/juce_audio_devices/juce_audio_devices.o

# target to build an object file
externals/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o
.PHONY : externals/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o

externals/JUCE/modules/juce_audio_devices/juce_audio_devices.i: externals/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i
.PHONY : externals/JUCE/modules/juce_audio_devices/juce_audio_devices.i

# target to preprocess a source file
externals/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i
.PHONY : externals/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i

externals/JUCE/modules/juce_audio_devices/juce_audio_devices.s: externals/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s
.PHONY : externals/JUCE/modules/juce_audio_devices/juce_audio_devices.s

# target to generate assembly for a file
externals/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s
.PHONY : externals/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s

externals/JUCE/modules/juce_audio_formats/juce_audio_formats.o: externals/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o
.PHONY : externals/JUCE/modules/juce_audio_formats/juce_audio_formats.o

# target to build an object file
externals/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o
.PHONY : externals/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o

externals/JUCE/modules/juce_audio_formats/juce_audio_formats.i: externals/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i
.PHONY : externals/JUCE/modules/juce_audio_formats/juce_audio_formats.i

# target to preprocess a source file
externals/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i
.PHONY : externals/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i

externals/JUCE/modules/juce_audio_formats/juce_audio_formats.s: externals/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s
.PHONY : externals/JUCE/modules/juce_audio_formats/juce_audio_formats.s

# target to generate assembly for a file
externals/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s
.PHONY : externals/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s

externals/JUCE/modules/juce_audio_processors/juce_audio_processors.o: externals/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o
.PHONY : externals/JUCE/modules/juce_audio_processors/juce_audio_processors.o

# target to build an object file
externals/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o
.PHONY : externals/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o

externals/JUCE/modules/juce_audio_processors/juce_audio_processors.i: externals/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i
.PHONY : externals/JUCE/modules/juce_audio_processors/juce_audio_processors.i

# target to preprocess a source file
externals/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i
.PHONY : externals/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i

externals/JUCE/modules/juce_audio_processors/juce_audio_processors.s: externals/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s
.PHONY : externals/JUCE/modules/juce_audio_processors/juce_audio_processors.s

# target to generate assembly for a file
externals/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s
.PHONY : externals/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s

externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.o: externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.mm.o
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.o

# target to build an object file
externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.mm.o
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.mm.o

externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.i: externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.mm.i
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.i

# target to preprocess a source file
externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.mm.i
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.mm.i

externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.s: externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.mm.s
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.s

# target to generate assembly for a file
externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.mm.s
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.mm.s

externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.o: externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.cpp.o
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.o

# target to build an object file
externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.cpp.o
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.cpp.o

externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.i: externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.cpp.i
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.i

# target to preprocess a source file
externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.cpp.i
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.cpp.i

externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.s: externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.cpp.s
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.s

# target to generate assembly for a file
externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.cpp.s
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.cpp.s

externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.o: externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.cpp.o
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.o

# target to build an object file
externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.cpp.o
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.cpp.o

externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.i: externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.cpp.i
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.i

# target to preprocess a source file
externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.cpp.i
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.cpp.i

externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.s: externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.cpp.s
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.s

# target to generate assembly for a file
externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.cpp.s
.PHONY : externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.cpp.s

externals/JUCE/modules/juce_audio_utils/juce_audio_utils.o: externals/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o
.PHONY : externals/JUCE/modules/juce_audio_utils/juce_audio_utils.o

# target to build an object file
externals/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o
.PHONY : externals/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o

externals/JUCE/modules/juce_audio_utils/juce_audio_utils.i: externals/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i
.PHONY : externals/JUCE/modules/juce_audio_utils/juce_audio_utils.i

# target to preprocess a source file
externals/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i
.PHONY : externals/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i

externals/JUCE/modules/juce_audio_utils/juce_audio_utils.s: externals/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s
.PHONY : externals/JUCE/modules/juce_audio_utils/juce_audio_utils.s

# target to generate assembly for a file
externals/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s
.PHONY : externals/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s

externals/JUCE/modules/juce_core/juce_core.o: externals/JUCE/modules/juce_core/juce_core.mm.o
.PHONY : externals/JUCE/modules/juce_core/juce_core.o

# target to build an object file
externals/JUCE/modules/juce_core/juce_core.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_core/juce_core.mm.o
.PHONY : externals/JUCE/modules/juce_core/juce_core.mm.o

externals/JUCE/modules/juce_core/juce_core.i: externals/JUCE/modules/juce_core/juce_core.mm.i
.PHONY : externals/JUCE/modules/juce_core/juce_core.i

# target to preprocess a source file
externals/JUCE/modules/juce_core/juce_core.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_core/juce_core.mm.i
.PHONY : externals/JUCE/modules/juce_core/juce_core.mm.i

externals/JUCE/modules/juce_core/juce_core.s: externals/JUCE/modules/juce_core/juce_core.mm.s
.PHONY : externals/JUCE/modules/juce_core/juce_core.s

# target to generate assembly for a file
externals/JUCE/modules/juce_core/juce_core.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_core/juce_core.mm.s
.PHONY : externals/JUCE/modules/juce_core/juce_core.mm.s

externals/JUCE/modules/juce_core/juce_core_CompilationTime.o: externals/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.o
.PHONY : externals/JUCE/modules/juce_core/juce_core_CompilationTime.o

# target to build an object file
externals/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.o
.PHONY : externals/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.o

externals/JUCE/modules/juce_core/juce_core_CompilationTime.i: externals/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i
.PHONY : externals/JUCE/modules/juce_core/juce_core_CompilationTime.i

# target to preprocess a source file
externals/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i
.PHONY : externals/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i

externals/JUCE/modules/juce_core/juce_core_CompilationTime.s: externals/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s
.PHONY : externals/JUCE/modules/juce_core/juce_core_CompilationTime.s

# target to generate assembly for a file
externals/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s
.PHONY : externals/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s

externals/JUCE/modules/juce_data_structures/juce_data_structures.o: externals/JUCE/modules/juce_data_structures/juce_data_structures.mm.o
.PHONY : externals/JUCE/modules/juce_data_structures/juce_data_structures.o

# target to build an object file
externals/JUCE/modules/juce_data_structures/juce_data_structures.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_data_structures/juce_data_structures.mm.o
.PHONY : externals/JUCE/modules/juce_data_structures/juce_data_structures.mm.o

externals/JUCE/modules/juce_data_structures/juce_data_structures.i: externals/JUCE/modules/juce_data_structures/juce_data_structures.mm.i
.PHONY : externals/JUCE/modules/juce_data_structures/juce_data_structures.i

# target to preprocess a source file
externals/JUCE/modules/juce_data_structures/juce_data_structures.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_data_structures/juce_data_structures.mm.i
.PHONY : externals/JUCE/modules/juce_data_structures/juce_data_structures.mm.i

externals/JUCE/modules/juce_data_structures/juce_data_structures.s: externals/JUCE/modules/juce_data_structures/juce_data_structures.mm.s
.PHONY : externals/JUCE/modules/juce_data_structures/juce_data_structures.s

# target to generate assembly for a file
externals/JUCE/modules/juce_data_structures/juce_data_structures.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_data_structures/juce_data_structures.mm.s
.PHONY : externals/JUCE/modules/juce_data_structures/juce_data_structures.mm.s

externals/JUCE/modules/juce_events/juce_events.o: externals/JUCE/modules/juce_events/juce_events.mm.o
.PHONY : externals/JUCE/modules/juce_events/juce_events.o

# target to build an object file
externals/JUCE/modules/juce_events/juce_events.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_events/juce_events.mm.o
.PHONY : externals/JUCE/modules/juce_events/juce_events.mm.o

externals/JUCE/modules/juce_events/juce_events.i: externals/JUCE/modules/juce_events/juce_events.mm.i
.PHONY : externals/JUCE/modules/juce_events/juce_events.i

# target to preprocess a source file
externals/JUCE/modules/juce_events/juce_events.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_events/juce_events.mm.i
.PHONY : externals/JUCE/modules/juce_events/juce_events.mm.i

externals/JUCE/modules/juce_events/juce_events.s: externals/JUCE/modules/juce_events/juce_events.mm.s
.PHONY : externals/JUCE/modules/juce_events/juce_events.s

# target to generate assembly for a file
externals/JUCE/modules/juce_events/juce_events.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_events/juce_events.mm.s
.PHONY : externals/JUCE/modules/juce_events/juce_events.mm.s

externals/JUCE/modules/juce_graphics/juce_graphics.o: externals/JUCE/modules/juce_graphics/juce_graphics.mm.o
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics.o

# target to build an object file
externals/JUCE/modules/juce_graphics/juce_graphics.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_graphics/juce_graphics.mm.o
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics.mm.o

externals/JUCE/modules/juce_graphics/juce_graphics.i: externals/JUCE/modules/juce_graphics/juce_graphics.mm.i
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics.i

# target to preprocess a source file
externals/JUCE/modules/juce_graphics/juce_graphics.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_graphics/juce_graphics.mm.i
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics.mm.i

externals/JUCE/modules/juce_graphics/juce_graphics.s: externals/JUCE/modules/juce_graphics/juce_graphics.mm.s
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics.s

# target to generate assembly for a file
externals/JUCE/modules/juce_graphics/juce_graphics.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_graphics/juce_graphics.mm.s
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics.mm.s

externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.o: externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.o
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.o

# target to build an object file
externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.o
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.o

externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.i: externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.i

# target to preprocess a source file
externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i

externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.s: externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.s

# target to generate assembly for a file
externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s

externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.o: externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.o
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.o

# target to build an object file
externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.o
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.o

externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.i: externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.i

# target to preprocess a source file
externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i

externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.s: externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.s

# target to generate assembly for a file
externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s
.PHONY : externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s

externals/JUCE/modules/juce_gui_basics/juce_gui_basics.o: externals/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o
.PHONY : externals/JUCE/modules/juce_gui_basics/juce_gui_basics.o

# target to build an object file
externals/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o
.PHONY : externals/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o

externals/JUCE/modules/juce_gui_basics/juce_gui_basics.i: externals/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i
.PHONY : externals/JUCE/modules/juce_gui_basics/juce_gui_basics.i

# target to preprocess a source file
externals/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i
.PHONY : externals/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i

externals/JUCE/modules/juce_gui_basics/juce_gui_basics.s: externals/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s
.PHONY : externals/JUCE/modules/juce_gui_basics/juce_gui_basics.s

# target to generate assembly for a file
externals/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s
.PHONY : externals/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s

externals/JUCE/modules/juce_gui_extra/juce_gui_extra.o: externals/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o
.PHONY : externals/JUCE/modules/juce_gui_extra/juce_gui_extra.o

# target to build an object file
externals/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o
.PHONY : externals/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o

externals/JUCE/modules/juce_gui_extra/juce_gui_extra.i: externals/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i
.PHONY : externals/JUCE/modules/juce_gui_extra/juce_gui_extra.i

# target to preprocess a source file
externals/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i
.PHONY : externals/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i

externals/JUCE/modules/juce_gui_extra/juce_gui_extra.s: externals/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s
.PHONY : externals/JUCE/modules/juce_gui_extra/juce_gui_extra.s

# target to generate assembly for a file
externals/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/externals/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s
.PHONY : externals/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s

src/audio/synth/SimpleSynth.o: src/audio/synth/SimpleSynth.cpp.o
.PHONY : src/audio/synth/SimpleSynth.o

# target to build an object file
src/audio/synth/SimpleSynth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/audio/synth/SimpleSynth.cpp.o
.PHONY : src/audio/synth/SimpleSynth.cpp.o

src/audio/synth/SimpleSynth.i: src/audio/synth/SimpleSynth.cpp.i
.PHONY : src/audio/synth/SimpleSynth.i

# target to preprocess a source file
src/audio/synth/SimpleSynth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/audio/synth/SimpleSynth.cpp.i
.PHONY : src/audio/synth/SimpleSynth.cpp.i

src/audio/synth/SimpleSynth.s: src/audio/synth/SimpleSynth.cpp.s
.PHONY : src/audio/synth/SimpleSynth.s

# target to generate assembly for a file
src/audio/synth/SimpleSynth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/audio/synth/SimpleSynth.cpp.s
.PHONY : src/audio/synth/SimpleSynth.cpp.s

src/controller/AppController.o: src/controller/AppController.cpp.o
.PHONY : src/controller/AppController.o

# target to build an object file
src/controller/AppController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/controller/AppController.cpp.o
.PHONY : src/controller/AppController.cpp.o

src/controller/AppController.i: src/controller/AppController.cpp.i
.PHONY : src/controller/AppController.i

# target to preprocess a source file
src/controller/AppController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/controller/AppController.cpp.i
.PHONY : src/controller/AppController.cpp.i

src/controller/AppController.s: src/controller/AppController.cpp.s
.PHONY : src/controller/AppController.s

# target to generate assembly for a file
src/controller/AppController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/controller/AppController.cpp.s
.PHONY : src/controller/AppController.cpp.s

src/model/CantusProblem.o: src/model/CantusProblem.cpp.o
.PHONY : src/model/CantusProblem.o

# target to build an object file
src/model/CantusProblem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/model/CantusProblem.cpp.o
.PHONY : src/model/CantusProblem.cpp.o

src/model/CantusProblem.i: src/model/CantusProblem.cpp.i
.PHONY : src/model/CantusProblem.i

# target to preprocess a source file
src/model/CantusProblem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/model/CantusProblem.cpp.i
.PHONY : src/model/CantusProblem.cpp.i

src/model/CantusProblem.s: src/model/CantusProblem.cpp.s
.PHONY : src/model/CantusProblem.s

# target to generate assembly for a file
src/model/CantusProblem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/model/CantusProblem.cpp.s
.PHONY : src/model/CantusProblem.cpp.s

src/model/ConstraintsSettings.o: src/model/ConstraintsSettings.cpp.o
.PHONY : src/model/ConstraintsSettings.o

# target to build an object file
src/model/ConstraintsSettings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/model/ConstraintsSettings.cpp.o
.PHONY : src/model/ConstraintsSettings.cpp.o

src/model/ConstraintsSettings.i: src/model/ConstraintsSettings.cpp.i
.PHONY : src/model/ConstraintsSettings.i

# target to preprocess a source file
src/model/ConstraintsSettings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/model/ConstraintsSettings.cpp.i
.PHONY : src/model/ConstraintsSettings.cpp.i

src/model/ConstraintsSettings.s: src/model/ConstraintsSettings.cpp.s
.PHONY : src/model/ConstraintsSettings.s

# target to generate assembly for a file
src/model/ConstraintsSettings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/model/ConstraintsSettings.cpp.s
.PHONY : src/model/ConstraintsSettings.cpp.s

src/service/GenerationService.o: src/service/GenerationService.cpp.o
.PHONY : src/service/GenerationService.o

# target to build an object file
src/service/GenerationService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/service/GenerationService.cpp.o
.PHONY : src/service/GenerationService.cpp.o

src/service/GenerationService.i: src/service/GenerationService.cpp.i
.PHONY : src/service/GenerationService.i

# target to preprocess a source file
src/service/GenerationService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/service/GenerationService.cpp.i
.PHONY : src/service/GenerationService.cpp.i

src/service/GenerationService.s: src/service/GenerationService.cpp.s
.PHONY : src/service/GenerationService.s

# target to generate assembly for a file
src/service/GenerationService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/service/GenerationService.cpp.s
.PHONY : src/service/GenerationService.cpp.s

src/ui/MainComponent.o: src/ui/MainComponent.cpp.o
.PHONY : src/ui/MainComponent.o

# target to build an object file
src/ui/MainComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/MainComponent.cpp.o
.PHONY : src/ui/MainComponent.cpp.o

src/ui/MainComponent.i: src/ui/MainComponent.cpp.i
.PHONY : src/ui/MainComponent.i

# target to preprocess a source file
src/ui/MainComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/MainComponent.cpp.i
.PHONY : src/ui/MainComponent.cpp.i

src/ui/MainComponent.s: src/ui/MainComponent.cpp.s
.PHONY : src/ui/MainComponent.s

# target to generate assembly for a file
src/ui/MainComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/MainComponent.cpp.s
.PHONY : src/ui/MainComponent.cpp.s

src/ui/WorkArea/WorkAreaPanel.o: src/ui/WorkArea/WorkAreaPanel.cpp.o
.PHONY : src/ui/WorkArea/WorkAreaPanel.o

# target to build an object file
src/ui/WorkArea/WorkAreaPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/WorkArea/WorkAreaPanel.cpp.o
.PHONY : src/ui/WorkArea/WorkAreaPanel.cpp.o

src/ui/WorkArea/WorkAreaPanel.i: src/ui/WorkArea/WorkAreaPanel.cpp.i
.PHONY : src/ui/WorkArea/WorkAreaPanel.i

# target to preprocess a source file
src/ui/WorkArea/WorkAreaPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/WorkArea/WorkAreaPanel.cpp.i
.PHONY : src/ui/WorkArea/WorkAreaPanel.cpp.i

src/ui/WorkArea/WorkAreaPanel.s: src/ui/WorkArea/WorkAreaPanel.cpp.s
.PHONY : src/ui/WorkArea/WorkAreaPanel.s

# target to generate assembly for a file
src/ui/WorkArea/WorkAreaPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/WorkArea/WorkAreaPanel.cpp.s
.PHONY : src/ui/WorkArea/WorkAreaPanel.cpp.s

src/ui/footer/FooterPanel.o: src/ui/footer/FooterPanel.cpp.o
.PHONY : src/ui/footer/FooterPanel.o

# target to build an object file
src/ui/footer/FooterPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/footer/FooterPanel.cpp.o
.PHONY : src/ui/footer/FooterPanel.cpp.o

src/ui/footer/FooterPanel.i: src/ui/footer/FooterPanel.cpp.i
.PHONY : src/ui/footer/FooterPanel.i

# target to preprocess a source file
src/ui/footer/FooterPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/footer/FooterPanel.cpp.i
.PHONY : src/ui/footer/FooterPanel.cpp.i

src/ui/footer/FooterPanel.s: src/ui/footer/FooterPanel.cpp.s
.PHONY : src/ui/footer/FooterPanel.s

# target to generate assembly for a file
src/ui/footer/FooterPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/footer/FooterPanel.cpp.s
.PHONY : src/ui/footer/FooterPanel.cpp.s

src/ui/header/HeaderPanel.o: src/ui/header/HeaderPanel.cpp.o
.PHONY : src/ui/header/HeaderPanel.o

# target to build an object file
src/ui/header/HeaderPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/header/HeaderPanel.cpp.o
.PHONY : src/ui/header/HeaderPanel.cpp.o

src/ui/header/HeaderPanel.i: src/ui/header/HeaderPanel.cpp.i
.PHONY : src/ui/header/HeaderPanel.i

# target to preprocess a source file
src/ui/header/HeaderPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/header/HeaderPanel.cpp.i
.PHONY : src/ui/header/HeaderPanel.cpp.i

src/ui/header/HeaderPanel.s: src/ui/header/HeaderPanel.cpp.s
.PHONY : src/ui/header/HeaderPanel.s

# target to generate assembly for a file
src/ui/header/HeaderPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/header/HeaderPanel.cpp.s
.PHONY : src/ui/header/HeaderPanel.cpp.s

src/ui/history/HistoryPanel.o: src/ui/history/HistoryPanel.cpp.o
.PHONY : src/ui/history/HistoryPanel.o

# target to build an object file
src/ui/history/HistoryPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/history/HistoryPanel.cpp.o
.PHONY : src/ui/history/HistoryPanel.cpp.o

src/ui/history/HistoryPanel.i: src/ui/history/HistoryPanel.cpp.i
.PHONY : src/ui/history/HistoryPanel.i

# target to preprocess a source file
src/ui/history/HistoryPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/history/HistoryPanel.cpp.i
.PHONY : src/ui/history/HistoryPanel.cpp.i

src/ui/history/HistoryPanel.s: src/ui/history/HistoryPanel.cpp.s
.PHONY : src/ui/history/HistoryPanel.s

# target to generate assembly for a file
src/ui/history/HistoryPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/history/HistoryPanel.cpp.s
.PHONY : src/ui/history/HistoryPanel.cpp.s

src/ui/keyboard/KeyboardComponent.o: src/ui/keyboard/KeyboardComponent.cpp.o
.PHONY : src/ui/keyboard/KeyboardComponent.o

# target to build an object file
src/ui/keyboard/KeyboardComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/keyboard/KeyboardComponent.cpp.o
.PHONY : src/ui/keyboard/KeyboardComponent.cpp.o

src/ui/keyboard/KeyboardComponent.i: src/ui/keyboard/KeyboardComponent.cpp.i
.PHONY : src/ui/keyboard/KeyboardComponent.i

# target to preprocess a source file
src/ui/keyboard/KeyboardComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/keyboard/KeyboardComponent.cpp.i
.PHONY : src/ui/keyboard/KeyboardComponent.cpp.i

src/ui/keyboard/KeyboardComponent.s: src/ui/keyboard/KeyboardComponent.cpp.s
.PHONY : src/ui/keyboard/KeyboardComponent.s

# target to generate assembly for a file
src/ui/keyboard/KeyboardComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/keyboard/KeyboardComponent.cpp.s
.PHONY : src/ui/keyboard/KeyboardComponent.cpp.s

src/ui/leftPanel/LeftPanel.o: src/ui/leftPanel/LeftPanel.cpp.o
.PHONY : src/ui/leftPanel/LeftPanel.o

# target to build an object file
src/ui/leftPanel/LeftPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/leftPanel/LeftPanel.cpp.o
.PHONY : src/ui/leftPanel/LeftPanel.cpp.o

src/ui/leftPanel/LeftPanel.i: src/ui/leftPanel/LeftPanel.cpp.i
.PHONY : src/ui/leftPanel/LeftPanel.i

# target to preprocess a source file
src/ui/leftPanel/LeftPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/leftPanel/LeftPanel.cpp.i
.PHONY : src/ui/leftPanel/LeftPanel.cpp.i

src/ui/leftPanel/LeftPanel.s: src/ui/leftPanel/LeftPanel.cpp.s
.PHONY : src/ui/leftPanel/LeftPanel.s

# target to generate assembly for a file
src/ui/leftPanel/LeftPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/leftPanel/LeftPanel.cpp.s
.PHONY : src/ui/leftPanel/LeftPanel.cpp.s

src/ui/main.o: src/ui/main.cpp.o
.PHONY : src/ui/main.o

# target to build an object file
src/ui/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/main.cpp.o
.PHONY : src/ui/main.cpp.o

src/ui/main.i: src/ui/main.cpp.i
.PHONY : src/ui/main.i

# target to preprocess a source file
src/ui/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/main.cpp.i
.PHONY : src/ui/main.cpp.i

src/ui/main.s: src/ui/main.cpp.s
.PHONY : src/ui/main.s

# target to generate assembly for a file
src/ui/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/main.cpp.s
.PHONY : src/ui/main.cpp.s

src/ui/optionsPanel/OptionsPanel.o: src/ui/optionsPanel/OptionsPanel.cpp.o
.PHONY : src/ui/optionsPanel/OptionsPanel.o

# target to build an object file
src/ui/optionsPanel/OptionsPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/optionsPanel/OptionsPanel.cpp.o
.PHONY : src/ui/optionsPanel/OptionsPanel.cpp.o

src/ui/optionsPanel/OptionsPanel.i: src/ui/optionsPanel/OptionsPanel.cpp.i
.PHONY : src/ui/optionsPanel/OptionsPanel.i

# target to preprocess a source file
src/ui/optionsPanel/OptionsPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/optionsPanel/OptionsPanel.cpp.i
.PHONY : src/ui/optionsPanel/OptionsPanel.cpp.i

src/ui/optionsPanel/OptionsPanel.s: src/ui/optionsPanel/OptionsPanel.cpp.s
.PHONY : src/ui/optionsPanel/OptionsPanel.s

# target to generate assembly for a file
src/ui/optionsPanel/OptionsPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/optionsPanel/OptionsPanel.cpp.s
.PHONY : src/ui/optionsPanel/OptionsPanel.cpp.s

src/ui/optionsPanel/OptionsPanelHelpers.o: src/ui/optionsPanel/OptionsPanelHelpers.cpp.o
.PHONY : src/ui/optionsPanel/OptionsPanelHelpers.o

# target to build an object file
src/ui/optionsPanel/OptionsPanelHelpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/optionsPanel/OptionsPanelHelpers.cpp.o
.PHONY : src/ui/optionsPanel/OptionsPanelHelpers.cpp.o

src/ui/optionsPanel/OptionsPanelHelpers.i: src/ui/optionsPanel/OptionsPanelHelpers.cpp.i
.PHONY : src/ui/optionsPanel/OptionsPanelHelpers.i

# target to preprocess a source file
src/ui/optionsPanel/OptionsPanelHelpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/optionsPanel/OptionsPanelHelpers.cpp.i
.PHONY : src/ui/optionsPanel/OptionsPanelHelpers.cpp.i

src/ui/optionsPanel/OptionsPanelHelpers.s: src/ui/optionsPanel/OptionsPanelHelpers.cpp.s
.PHONY : src/ui/optionsPanel/OptionsPanelHelpers.s

# target to generate assembly for a file
src/ui/optionsPanel/OptionsPanelHelpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/optionsPanel/OptionsPanelHelpers.cpp.s
.PHONY : src/ui/optionsPanel/OptionsPanelHelpers.cpp.s

src/ui/optionsPanel/OptionsPanelStyle.o: src/ui/optionsPanel/OptionsPanelStyle.cpp.o
.PHONY : src/ui/optionsPanel/OptionsPanelStyle.o

# target to build an object file
src/ui/optionsPanel/OptionsPanelStyle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/optionsPanel/OptionsPanelStyle.cpp.o
.PHONY : src/ui/optionsPanel/OptionsPanelStyle.cpp.o

src/ui/optionsPanel/OptionsPanelStyle.i: src/ui/optionsPanel/OptionsPanelStyle.cpp.i
.PHONY : src/ui/optionsPanel/OptionsPanelStyle.i

# target to preprocess a source file
src/ui/optionsPanel/OptionsPanelStyle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/optionsPanel/OptionsPanelStyle.cpp.i
.PHONY : src/ui/optionsPanel/OptionsPanelStyle.cpp.i

src/ui/optionsPanel/OptionsPanelStyle.s: src/ui/optionsPanel/OptionsPanelStyle.cpp.s
.PHONY : src/ui/optionsPanel/OptionsPanelStyle.s

# target to generate assembly for a file
src/ui/optionsPanel/OptionsPanelStyle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/optionsPanel/OptionsPanelStyle.cpp.s
.PHONY : src/ui/optionsPanel/OptionsPanelStyle.cpp.s

src/ui/optionsPanel/components/VoiceBox.o: src/ui/optionsPanel/components/VoiceBox.cpp.o
.PHONY : src/ui/optionsPanel/components/VoiceBox.o

# target to build an object file
src/ui/optionsPanel/components/VoiceBox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/optionsPanel/components/VoiceBox.cpp.o
.PHONY : src/ui/optionsPanel/components/VoiceBox.cpp.o

src/ui/optionsPanel/components/VoiceBox.i: src/ui/optionsPanel/components/VoiceBox.cpp.i
.PHONY : src/ui/optionsPanel/components/VoiceBox.i

# target to preprocess a source file
src/ui/optionsPanel/components/VoiceBox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/optionsPanel/components/VoiceBox.cpp.i
.PHONY : src/ui/optionsPanel/components/VoiceBox.cpp.i

src/ui/optionsPanel/components/VoiceBox.s: src/ui/optionsPanel/components/VoiceBox.cpp.s
.PHONY : src/ui/optionsPanel/components/VoiceBox.s

# target to generate assembly for a file
src/ui/optionsPanel/components/VoiceBox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/myproject.dir/build.make CMakeFiles/myproject.dir/src/ui/optionsPanel/components/VoiceBox.cpp.s
.PHONY : src/ui/optionsPanel/components/VoiceBox.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... damien"
	@echo "... myproject"
	@echo "... externals/JUCE/modules/juce_audio_basics/juce_audio_basics.o"
	@echo "... externals/JUCE/modules/juce_audio_basics/juce_audio_basics.i"
	@echo "... externals/JUCE/modules/juce_audio_basics/juce_audio_basics.s"
	@echo "... externals/JUCE/modules/juce_audio_devices/juce_audio_devices.o"
	@echo "... externals/JUCE/modules/juce_audio_devices/juce_audio_devices.i"
	@echo "... externals/JUCE/modules/juce_audio_devices/juce_audio_devices.s"
	@echo "... externals/JUCE/modules/juce_audio_formats/juce_audio_formats.o"
	@echo "... externals/JUCE/modules/juce_audio_formats/juce_audio_formats.i"
	@echo "... externals/JUCE/modules/juce_audio_formats/juce_audio_formats.s"
	@echo "... externals/JUCE/modules/juce_audio_processors/juce_audio_processors.o"
	@echo "... externals/JUCE/modules/juce_audio_processors/juce_audio_processors.i"
	@echo "... externals/JUCE/modules/juce_audio_processors/juce_audio_processors.s"
	@echo "... externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.o"
	@echo "... externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.i"
	@echo "... externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless.s"
	@echo "... externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.o"
	@echo "... externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.i"
	@echo "... externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_ara.s"
	@echo "... externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.o"
	@echo "... externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.i"
	@echo "... externals/JUCE/modules/juce_audio_processors_headless/juce_audio_processors_headless_lv2_libs.s"
	@echo "... externals/JUCE/modules/juce_audio_utils/juce_audio_utils.o"
	@echo "... externals/JUCE/modules/juce_audio_utils/juce_audio_utils.i"
	@echo "... externals/JUCE/modules/juce_audio_utils/juce_audio_utils.s"
	@echo "... externals/JUCE/modules/juce_core/juce_core.o"
	@echo "... externals/JUCE/modules/juce_core/juce_core.i"
	@echo "... externals/JUCE/modules/juce_core/juce_core.s"
	@echo "... externals/JUCE/modules/juce_core/juce_core_CompilationTime.o"
	@echo "... externals/JUCE/modules/juce_core/juce_core_CompilationTime.i"
	@echo "... externals/JUCE/modules/juce_core/juce_core_CompilationTime.s"
	@echo "... externals/JUCE/modules/juce_data_structures/juce_data_structures.o"
	@echo "... externals/JUCE/modules/juce_data_structures/juce_data_structures.i"
	@echo "... externals/JUCE/modules/juce_data_structures/juce_data_structures.s"
	@echo "... externals/JUCE/modules/juce_events/juce_events.o"
	@echo "... externals/JUCE/modules/juce_events/juce_events.i"
	@echo "... externals/JUCE/modules/juce_events/juce_events.s"
	@echo "... externals/JUCE/modules/juce_graphics/juce_graphics.o"
	@echo "... externals/JUCE/modules/juce_graphics/juce_graphics.i"
	@echo "... externals/JUCE/modules/juce_graphics/juce_graphics.s"
	@echo "... externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.o"
	@echo "... externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.i"
	@echo "... externals/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.s"
	@echo "... externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.o"
	@echo "... externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.i"
	@echo "... externals/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.s"
	@echo "... externals/JUCE/modules/juce_gui_basics/juce_gui_basics.o"
	@echo "... externals/JUCE/modules/juce_gui_basics/juce_gui_basics.i"
	@echo "... externals/JUCE/modules/juce_gui_basics/juce_gui_basics.s"
	@echo "... externals/JUCE/modules/juce_gui_extra/juce_gui_extra.o"
	@echo "... externals/JUCE/modules/juce_gui_extra/juce_gui_extra.i"
	@echo "... externals/JUCE/modules/juce_gui_extra/juce_gui_extra.s"
	@echo "... src/audio/synth/SimpleSynth.o"
	@echo "... src/audio/synth/SimpleSynth.i"
	@echo "... src/audio/synth/SimpleSynth.s"
	@echo "... src/controller/AppController.o"
	@echo "... src/controller/AppController.i"
	@echo "... src/controller/AppController.s"
	@echo "... src/model/CantusProblem.o"
	@echo "... src/model/CantusProblem.i"
	@echo "... src/model/CantusProblem.s"
	@echo "... src/model/ConstraintsSettings.o"
	@echo "... src/model/ConstraintsSettings.i"
	@echo "... src/model/ConstraintsSettings.s"
	@echo "... src/service/GenerationService.o"
	@echo "... src/service/GenerationService.i"
	@echo "... src/service/GenerationService.s"
	@echo "... src/ui/MainComponent.o"
	@echo "... src/ui/MainComponent.i"
	@echo "... src/ui/MainComponent.s"
	@echo "... src/ui/WorkArea/WorkAreaPanel.o"
	@echo "... src/ui/WorkArea/WorkAreaPanel.i"
	@echo "... src/ui/WorkArea/WorkAreaPanel.s"
	@echo "... src/ui/footer/FooterPanel.o"
	@echo "... src/ui/footer/FooterPanel.i"
	@echo "... src/ui/footer/FooterPanel.s"
	@echo "... src/ui/header/HeaderPanel.o"
	@echo "... src/ui/header/HeaderPanel.i"
	@echo "... src/ui/header/HeaderPanel.s"
	@echo "... src/ui/history/HistoryPanel.o"
	@echo "... src/ui/history/HistoryPanel.i"
	@echo "... src/ui/history/HistoryPanel.s"
	@echo "... src/ui/keyboard/KeyboardComponent.o"
	@echo "... src/ui/keyboard/KeyboardComponent.i"
	@echo "... src/ui/keyboard/KeyboardComponent.s"
	@echo "... src/ui/leftPanel/LeftPanel.o"
	@echo "... src/ui/leftPanel/LeftPanel.i"
	@echo "... src/ui/leftPanel/LeftPanel.s"
	@echo "... src/ui/main.o"
	@echo "... src/ui/main.i"
	@echo "... src/ui/main.s"
	@echo "... src/ui/optionsPanel/OptionsPanel.o"
	@echo "... src/ui/optionsPanel/OptionsPanel.i"
	@echo "... src/ui/optionsPanel/OptionsPanel.s"
	@echo "... src/ui/optionsPanel/OptionsPanelHelpers.o"
	@echo "... src/ui/optionsPanel/OptionsPanelHelpers.i"
	@echo "... src/ui/optionsPanel/OptionsPanelHelpers.s"
	@echo "... src/ui/optionsPanel/OptionsPanelStyle.o"
	@echo "... src/ui/optionsPanel/OptionsPanelStyle.i"
	@echo "... src/ui/optionsPanel/OptionsPanelStyle.s"
	@echo "... src/ui/optionsPanel/components/VoiceBox.o"
	@echo "... src/ui/optionsPanel/components/VoiceBox.i"
	@echo "... src/ui/optionsPanel/components/VoiceBox.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/chris/Documents/Mémoire/myproject/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

